名字: 签到 # yml文件名
 
在:
工作流_调度:
日程安排:   
    # https://crontab.guru/
    #世界协调时时间,中国时区应减8
    # ┌──────────一分钟(0 - 59)
    # │ ┌────────时间(0 - 23)
    # │ │每月的┌──────日(1 - 31)
    # │ │ │ ┌────月(1 - 12月或1-12月)
    #│││┌──一周中的某一天(0 - 6或周六)
    #         │ │ │ │ │
    - 时间单位: '0 8 * * *'
 
工作:
运行-检入: # 任务名
连续运行: ubuntu-latest
步伐:
      - 名字: Checkout repository
使用: actions/checkout@v3
        
      - 使用: actions/setup-node@v3
随着:
节点版本: 20.x '
          
      - 名字: -姓名:安装依赖
奔跑: |
npm安装

-姓名:运行签到
运行:
          node ./index.js '${{ secrets.XYB }}'
