名字: 名字：签到# yml文件名# yml文件名
 
在:
工作流_调度:
日程安排:   
# https://crontab.guru/# https://crontab.guru/
    #世界协调时时间,中国时区应减8
    # ┌──────────一分钟(0 - 59)
    # │ ┌────────时间(0 - 23)
    # │ │每月的┌──────日(1 - 31)
    # │ │ │ ┌────月(1 - 12月或1-12月)
    #│││┌──一周中的某一天(0 - 6或周六)
    #         │ │ │ │ │
    - 时间单位: '0 8 * * *'
 
工作:
运行-检入: # 任务名
连续运行: 连续运行:Ubuntu-最新版
步伐:
      - 名字: 签出存储库
使用: 使用：动作/签出@v3
        
      - 使用: -使用：动作/设置-节点@v3
随着:
节点版本: 节点版本:20.x ''
          
      - 名字: -姓名:安装依赖
奔跑: |
npm安装

-姓名:运行签到
运行:
节点。/索引. js{{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} ${{机密。XYB }} '
